# ----------------------------------------------------------------------------
#
# Package             : querystring
# Source Repo         : https://github.com/get/querystring
# Travis Job Link     : https://travis-ci.com/github/asellappen/querystring/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
sudo: false
language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - '14'
  - '15'
script:
  - npm install
  - npm run test test.js
